### ISSUE TITLE
Nonalphanumeric characters cause crashes

### ISSUE THREAD

**Issue by AndreasRoither** [p-yukusai/PyWall#7] opened 2022-02-04 09:37 UTC
Good work on the last issue! I found another bug!

**Describe the bug**
I noticed that in some instances a `.exe` would not be added to the firewall. It happens when a a folder has non alphanumeric characters in it. An example would be the character `╔`. Some characters like `©`. Not all nonalphanumeric characters seem to cause a problem though.

**To Reproduce**
1. Have a folder with a special character in it like: `╔`
2. Allow/Deny access via context menu on that specific folder

**Expected behavior**
No error or maybe a notification.

**Error Log**
Here are some error logs:

```bash
root - ERROR - Runtime error is "'charmap' codec can't encode characters in position 59-60: 
    character maps to <undefined>", 
see full traceback bellow: 
 
Traceback (most recent call last):
  File "src\cmdWorker.py", line 86, in access_handler
    print(Path(y))
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 59-60: character maps to <undefined>
```

```bash
Traceback (most recent call last):
  File "main.py", line 63, in <module>
  File "src\logger.py", line 7, in actionLogger
    print(actionLogged)
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u253c' in position 64: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 86, in <module>
  File "src\logger.py", line 27, in logException
    actionLogger(f'Exception logged, runtime error is "{Critical}"')
  File "src\logger.py", line 7, in actionLogger
    print(actionLogged)
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u253c' in position 138: character maps to <undefined>
```

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Education
 - Version	10.0.22000 Build 22000

**Additional context**
Now I had a look at the source code at line:
```python
                    if z in Path(y).suffix and Path(y).stem not in ignoredFiles:
                        print(Path(y))
                        allFiles.append(Path(y))
```
The error seems to be at the `print()` statement from what I can tell. This might be an error in the library you are using (`from pathlib import Path`), when the `Path(y)` is converted to a string.
Some libraries allow to set the encoding like, `io`:
```python
import io
with io.open(filename,'r',encoding='utf8') as f:
    text = f.read()
```
But I did not look into the `pathlib` library further. It could also be that the error logs are inconclusive and the error happens somewhere further up the chain, you could debug it and see what happens.

A few options could be:
1. Find out if you can set encoding for the library
2. Try catch exception and skip folder if it happens (so at least other folders are added)
   - Maybe a message would be good
3. Use another library that handles characters correctly

Have fun!

**Comment by p-yukusai** [comment] 2022-02-04 14:50
As always, anything not unicode will cause issues when coding 😞 
While debugging I noticed that this bug is not related to the pathlib library but rather it is indeed caused by the print method, this has been fixed by just converting the action into a string prior to printing it, and just in case I made it so in case of a UnicodeError it will encode to utf-8, this is a little overkill, but that's just how it be 😎 
I'll be pushing the changes and making a new release real soon, so look forward to it!
Thanks for the bug report!

**Closed as completed by p-yukusai** 2022-02-04 14:50 UTC
Labels: bug
